### PR TITLE
[ready to publish with videos] Acknowledgements

### PR DESCRIPTION
**Pull request by slhenry**

### CODE REVIEW

**Comment by hidde** [comment]
If these are ready for publication, shall we merge this branch?

**Comment by slhenry** [comment]
Is there a reason to do it now, versus waiting until everything is ready to publish?

**Comment by hidde** [comment]
We could then strike it from our to do lists

**Comment by slhenry** [comment]
Given the current challenges with publishing regenerated site, I'd rather wait.

I think need to synch with adding it to nav - PR https://github.com/w3c/wai-website-data/pull/25

I'd like to do a simple site regen before doing these more complex things.

**Pull request merged**
