### PR TITLE
Fix typo in Fork & edit link

### PR DESCRIPTION
**Pull request by remibetin**
The current link returns a 404.

💡 I suggest to "squash and merge" this PR to get a cleaner history.

### CODE REVIEW

**Comment by SteveALee** [comment]
@shawna-slh This looks good to go to me. The only diff from master is now the broken link.

**Review by SteveALee — COMMENTED** [review]
@remibetin - apologies for the delay - the notification got lost in my inbox :(

Looks good to go - thanks.

@shawna-slh I'm not clear on the workflow here. Who commits?

**Comment by remibetin** [comment]
@SteveALee No problem !

To help you find my PRs, here is a list of the similar "technical" ones I opened recently (I am not always able to request your review) :
- https://github.com/w3c/wai-std-gl-overview/pull/63
- https://github.com/w3c/wai-perspective-videos/pull/45
- https://github.com/w3c/wai-accessibility-principles/pull/43
- https://github.com/w3c/wai-intro-accessibility/pull/69
- https://github.com/w3c/wai-about-wai/pull/88
- https://github.com/w3c/wai-eval-tools-overview/pull/10
- https://github.com/w3c/wai-first-aid/pull/10

**Comment by remibetin** [comment]
@shawna-slh Just so you know, here are the other PRs I've submitted for the translation project :

Syncing VTTs and tables :
- https://github.com/w3c/wai-eval-tools-overview/pull/11
- https://github.com/w3c/wai-InvolveUsersEval/pull/24
- https://github.com/w3c/wai-conformance-eval-overview/pull/11

Fixing a broken PR :
- https://github.com/w3c/wai-intro-atag/pull/15

Updating Audio & Video Media translation :
- https://github.com/w3c/wai-media-guide/pull/177
- Then https://github.com/w3c/wai-website-data/pull/75 will be needed.

**Pull request merged**
