### PR TITLE
[delete now that replaced?] Add evaluation videos to overview

### PR DESCRIPTION
**Pull request by hidde**
@slhenry @nitedog Ready for your review: the first overview page with:

- first video player is AblePlayer with link to transcript
- other video players are regular `<video>` elements with link to page with more accessible version

Captions are missing, as I did not receive `.vtt` files yet.

[Preview](https://deploy-preview-17--wai-eval-overview.netlify.com/test-evaluate/)

### CODE REVIEW

**Comment by slhenry** [comment]
Hi Hidde! Great to see this coming along. A few things:
* [ ] I'm not getting the AblePlayer controls (first video)
* [ ] The links underneath the other videos should go directly to the video. I guess on the Tools Overview and Conformance Overview, that should be be the H1.  And for the others, the new H2.
* [ ] footer updates missing

**Comment by hidde** [comment]
Issue from Shawn that describes how to include text transcript: https://github.com/w3c/wai-eval-overview/issues/19

**Comment by hidde** [comment]
Information about footers:

```change:
[[
<p>Developed with input from the Education and Outreach Working Group (<a href="http://www.w3.org/WAI/EO/">EOWG</a>).</p>
'']]

to:
[[
<p>Videos developed by the Education and Outreach Working Group (<a href="http://www.w3.org/WAI/EO/">EOWG</a>) with support from the <a href="https://www.w3.org/WAI/about/projects/wai-guide/">WAI-Guide</a> project funded by the European Commission (EC) under the Horizon 2020 program (Grant Agreement 822245). <a href="@@">Acknowledgments</a>.</p>
'']]

and update date:
[[
<p><strong>Date:</strong> Updated 00 March 2020.</p>
]]
```

**Comment by hidde** [comment]
Updates: 

- AblePlayer controls: the controls did not render, because the caption file I linked does not yet exist, have removed captions from now
- Updated footer text 
- To first video, added a link to newly created alternatives section, per @slhenry's suggestions

**Comment by slhenry** [comment]
Since this is under hidde: instead of w3c: , I couldn't work with it directly. So I did another pull request

https://github.com/w3c/wai-eval-overview/pull/21

I assume close this one?

**Comment by hidde** [comment]
@slhenry Thanks, closing this as it now exists as #21

**Pull request closed without merging**
